name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.x'

      #- name: GO111MODULE
      #  run: go env -w GO111MODULE=on

      - name: Mod init
        run: |
           go mod init github.com/imneov/siphon/siphon

      - name: Install dependencies
        run: |
           go get github.com/thinkboy/log4go
           go get github.com/reborndb/go/log
           go get github.com/reborndb/go/errors
           go get github.com/reborndb/go/atomic2
           go get github.com/garyburd/redigo/redis
           go get github.com/docopt/docopt-go
           go get github.com/seefan/goerr@v1.0.0

      - name: Install ssdb
        run: |
           go get github.com/imneov/siphon/ssdb
      - name: Build siphon
        run: |
           go build github.com/imneov/siphon/siphon

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./
