name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Install dependencies
        run: |
          go get github.com/thinkboy/log4go
          go get github.com/reborndb/go/log
          go get github.com/reborndb/go/errors
          go get github.com/reborndb/go/atomic2
          go get github.com/imneov/siphon/ssdb
          go get github.com/garyburd/redigo/redis
          go get github.com/docopt/docopt-go

      - name: Build
        run: go build -v ./siphon
